### PR TITLE
Fix async userdata __index, __newindex metamethods

### LINKED ISSUE #134: Async index metamethod
Look at the following code:
```
use std::sync::Arc;

use mlua::{Lua, UserData, UserDataMethods, MetaMethod, chunk, Result};

#[derive(Clone)]
struct TestUserData {
    //
}

impl UserData for TestUserData {
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_async_method("test_method", |_lua, data, ()| async move {
            tokio::time::sleep(
                tokio::time::Duration::from_millis(20)
            ).await;
            Ok(1)
        });

        methods.add_async_meta_method(MetaMethod::Index, |_lua, data, index: String| async move {
            tokio::time::sleep(
                tokio::time::Duration::from_millis(20)
            ).await;
            Ok(index)
        });
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let lua = Arc::new(Lua::new());

    lua.globals().set("test_user_data", lua.create_userdata(TestUserData {})?)?;

    lua.load(chunk! {
        test_user_data:test_method()
        print(test_user_data.test)
    }).exec_async().await?;

    println!("Hello, world!");

    Ok(())
}
```

It causes and error "attempt to yield across a C-call boundary". From my investigation, I found out that in this case, index metamethod is actually handled by this function which is causes the problem: https://github.com/khvzak/mlua/blob/master/src/util.rs#L365

### PR DESCRIPTION
**Pull request by Tarik02**
Fixes #134

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -345,6 +345,52 @@ pub unsafe fn get_gc_userdata<T: Any>(state: *mut ffi::lua_State, index: c_int)
     ud
 }
 
+pub unsafe fn init_userdata_metatable_index(
+    state: *mut ffi::lua_State
+) -> Result<()> {
+    match ffi::luaL_dostring(state, cstr!(r#"return function (__index, field_getters, methods)
+        return function (self, key)
+            if field_getters ~= nil and rawget(field_getters, key) ~= nil then
+                return field_getters[key](self)
```
Comment (khvzak) [inline src/util.rs:354]: I don't think that we can rely on presence of `rawget` method. It can be not available.
Also you do double lookup, first to check the condition then in the block body.

File: src/util.rs [hunk 2]
```diff
@@ -345,6 +345,52 @@ pub unsafe fn get_gc_userdata<T: Any>(state: *mut ffi::lua_State, index: c_int)
     ud
 }
 
+pub unsafe fn init_userdata_metatable_index(
+    state: *mut ffi::lua_State
+) -> Result<()> {
+    match ffi::luaL_dostring(state, cstr!(r#"return function (__index, field_getters, methods)
```
Comment (khvzak) [inline src/util.rs:351]: `luaL_dostring` is marked as `m` and can trigger memory errors (if it's set via `set_memory_limit()`) which cause unprotected crash.

File: src/util.rs [hunk 3]
```diff
@@ -345,6 +345,52 @@ pub unsafe fn get_gc_userdata<T: Any>(state: *mut ffi::lua_State, index: c_int)
...
+            if field_getters ~= nil and rawget(field_getters, key) ~= nil then
+                return field_getters[key](self)
+            elseif methods ~= nil and methods[key] ~= nil then
+                return methods[key]
+            elseif type(__index) == 'table' then
+                return rawget(__index, key)
+            elseif type(__index) == 'function' then
+                return __index(self, key)
+            else
+                error(string.format('attempt to get an unknown field \'%s\'', key))
```
Comment (khvzak) [inline src/util.rs:362]: `string` module can simply be not available or be not a standard module.
Strictly speaking we cannot rely on `type` and `rawset` methods as well.

File: src/util.rs [hunk 4]
```diff
@@ -345,6 +345,52 @@ pub unsafe fn get_gc_userdata<T: Any>(state: *mut ffi::lua_State, index: c_int)
...
+            end
+        end
+    end"#)) {
+        0 => Ok(()),
```
Comment (khvzak) [inline src/util.rs:366]: would be better to use  ffi::LUA_OK instead of 0

File: src/util.rs [hunk 5]
```diff
@@ -462,9 +422,8 @@ pub unsafe fn init_userdata_metatable<T>(
                         ffi::lua_pushnil(state);
                     }
                 }
-                protect_lua!(state, 3, 1, fn(state) {
-                    ffi::lua_pushcclosure(state, meta_index_impl, 3);
-                })?;
+
+                ffi::lua_call(state, 3, 1);
```
Comment (khvzak) [inline src/util.rs:426]: `ffi::lua_call` is unprotected call and can cause a crash

**Review by khvzak — COMMENTED** [review]
Thanks, it's a valid way to allow yelding in index lookups (ie. make them async).

What is your Lua version and have you done any benchmarking?

File: src/util.rs (hunk 3 above)
Comment (Tarik02) [reply src/util.rs:362]: +error too

**Comment by Tarik02** [comment]
> Thanks, it's a valid way to allow yelding in index lookups (ie. make them async).
> 
> What is your Lua version and have you done any benchmarking?

I tested only in lua54 and didn't do any benchmarking yet.

**Comment by Tarik02** [comment]
tested all versions, all tests are passing

**Comment by Tarik02** [comment]
master:
```
index [table userdata] 10                                                                            
                        time:   [4.1560 us 4.1826 us 4.2121 us]
                        change: [+1.4832% +2.2542% +3.0528%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 26 outliers among 300 measurements (8.67%)
  15 (5.00%) high mild
  11 (3.67%) high severe
```

fix/async_userdata_index_newindex:
```
index [table userdata] 10                                                                            
                        time:   [4.0235 us 4.0449 us 4.0688 us]
                        change: [-4.1618% -3.4286% -2.7413%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 35 outliers among 300 measurements (11.67%)
  4 (1.33%) high mild
  31 (10.33%) high severe
```
